package com.aurasentinel.gateway.model;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.time.Instant;
import java.util.Map;

// DTO que representa um evento de telemetria de segurança enviado pelo Agente.
public class TelemetryEvent {

    // Unique identifier of the event, generated by the Agent.
    @NotBlank(message = "The event ID cannot be empty.")
    private String eventId;

    // Unique identifier of the machine (endpoint) where the event occurred.
    @NotBlank(message = "The endpoint ID cannot be empty.")
    @Size(max = 128, message = "The endpoint ID exceeds 128 characters.")
    private String endpointId;

    // ID of the user or system account that triggered the event.
    @NotBlank(message = "The user ID cannot be empty.")
    private String userId;

    // Type of event: e.g., FILE_WRITE, AUTH_FAIL, PROCESS_LAUNCH, DECOY_ACCESS.
    @NotBlank(message = "The event type must be specified.")
    @Pattern(regexp = "^[A-Z_]+$", message = "The event type must be in CAPITALS.")
    private String eventType;

    // Timestamp of the event occurrence in the source system (Agent).
    @NotNull(message = "The timestamp cannot be null.")
    private Instant timestamp;

    // Specific context data for the event (e.g., file path, executed command).
    @NotNull(message = "Context data cannot be null.")
    private Map<String, Object> contextData;

    // Constructor vazio para desserialização
    public TelemetryEvent() {}

    // Construtor completo
    public TelemetryEvent(String eventId, String endpointId, String userId, String eventType, Instant timestamp, Map<String, Object> contextData) {
        this.eventId = eventId;
        this.endpointId = endpointId;
        this.userId = userId;
        this.eventType = eventType;
        this.timestamp = timestamp;
        this.contextData = contextData;
    }

    // --- Getters e Setters (Omitidos para brevidade) ---

    public String getEventId() { return eventId; }
    public void setEventId(String eventId) { this.eventId = eventId; }
    public String getEndpointId() { return endpointId; }
    public void setEndpointId(String endpointId) { this.endpointId = endpointId; }
    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }
    public String getEventType() { return eventType; }
    public void setEventType(String eventType) { this.eventType = eventType; }
    public Instant getTimestamp() { return timestamp; }
    public void setTimestamp(Instant timestamp) { this.timestamp = timestamp; }
    public Map<String, Object> getContextData() { return contextData; }
    public void setContextData(Map<String, Object> contextData) { this.contextData = contextData; }
}